# Generated by Django 3.0 on 2020-04-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(auto_created=True)),
                ('state_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
