# Generated by Django 3.0 on 2020-04-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0002_adminstatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstatemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='adminstatemodel',
            name='state_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
