# Generated by Django 3.0 on 2020-04-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0003_auto_20200417_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCityTable',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AdminStateModel')),
            ],
        ),
    ]
