# Generated by Django 3.0 on 2020-04-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0004_admincitytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincitytable',
            name='city_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
