# Generated by Django 3.0 on 2020-04-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0005_auto_20200420_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAreaModel',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AdminCityTable')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AdminStateModel')),
            ],
        ),
    ]
