# Generated by Django 3.0 on 2020-04-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0006_adminareamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminareamodel',
            name='state',
        ),
    ]
