# Generated by Django 3.0 on 2020-04-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0007_remove_adminareamodel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRestaurantTypeModel',
            fields=[
                ('restaurant_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_type_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adminareamodel',
            name='area_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
