# Generated by Django 3.0 on 2020-04-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_admin', '0008_auto_20200423_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRegistrationModel',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_contact_no', models.IntegerField(unique=True)),
                ('restaurant_Email', models.EmailField(max_length=254)),
                ('restaurant_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AdminAreaModel')),
                ('restaurant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AdminRestaurantTypeModel')),
            ],
        ),
    ]
