# Generated by Django 3.0 on 2020-04-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantregistrationmodel',
            name='restaurant_otp',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantregistrationmodel',
            name='restaurant_password',
            field=models.CharField(default=1.0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantregistrationmodel',
            name='restaurant_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
