# Generated by Django 3.0 on 2020-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200427_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantregistrationmodel',
            name='restaurant_password',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
