# Generated by Django 3.0 on 2020-04-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20200427_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantregistrationmodel',
            name='restaurant_otp',
        ),
    ]
